services:
  lanscope:
    build: .
    image: ghcr.io/dannyruizb/lanscope:0.13.1
    container_name: lanscope
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped
    environment:
      PORT: 3030
      DB_PATH: /var/lib/lanscope/lanscope.db
    volumes:
      - lanscope-data:/var/lib/lanscope

volumes:
  lanscope-data:
